name: Livter Android Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install python-for-android
        run: |
          python -m pip install --upgrade pip
          pip install python-for-android

      - name: Check pygame recipe
        run: |
          p4a recipes | grep -i pygame || true